version: "3.9"
   
services:
  web3:
    build: .
    command: python manage.py runserver  0.0.0.0:8003
    volumes:
      - .:/usr/src/app
    environment: 
      - PYTHONUNBUFFERED=1
    ports:
      - "8003:8003"


  